name: PR Commands

on:
  issue_comment:
    types: [created, edited, deleted]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  handle-command:
    name: Handle PR Command
    if: github.event.issue.pull_request
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout CODEOWNERS
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 1
          sparse-checkout: |
            .github/CODEOWNERS

      - name: Execute command
        uses: docker://ghcr.io/bartsmykla/smyklot:1.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          COMMENT_ID: ${{ github.event.comment.id }}
          COMMENT_ACTION: ${{ github.event.action }}
          PR_NUMBER: ${{ github.event.issue.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          COMMENT_AUTHOR: ${{ github.event.comment.user.login }}
